import _defineProperty from '@babel/runtime/helpers/defineProperty';

var _DURATION_DECIMAL_DIG;
var DEFAULT_NUMBER_FORMAT = 'number';
var DURATION_FORMATS_MAP = {
  H_MM: 'h:mm',
  H_MM_SS: 'h:mm:ss',
  H_MM_SS_S: 'h:mm:ss.s',
  H_MM_SS_SS: 'h:mm:ss.ss',
  H_MM_SS_SSS: 'h:mm:ss.sss'
};
var DURATION_FORMATS = [{
  name: DURATION_FORMATS_MAP.H_MM,
  type: DURATION_FORMATS_MAP.H_MM
}, {
  name: DURATION_FORMATS_MAP.H_MM_SS,
  type: DURATION_FORMATS_MAP.H_MM_SS
}];
var DURATION_DECIMAL_DIGITS = (_DURATION_DECIMAL_DIG = {}, _defineProperty(_DURATION_DECIMAL_DIG, DURATION_FORMATS_MAP.H_MM, 0), _defineProperty(_DURATION_DECIMAL_DIG, DURATION_FORMATS_MAP.H_MM_SS, 0), _defineProperty(_DURATION_DECIMAL_DIG, DURATION_FORMATS_MAP.H_MM_SS_S, 1), _defineProperty(_DURATION_DECIMAL_DIG, DURATION_FORMATS_MAP.H_MM_SS_SS, 2), _defineProperty(_DURATION_DECIMAL_DIG, DURATION_FORMATS_MAP.H_MM_SS_SSS, 3), _DURATION_DECIMAL_DIG);

export { DEFAULT_NUMBER_FORMAT, DURATION_DECIMAL_DIGITS, DURATION_FORMATS, DURATION_FORMATS_MAP };
