const DEFAULT_NUMBER_FORMAT = 'number';

const DURATION_FORMATS_MAP = {
  H_MM: 'h:mm',
  H_MM_SS: 'h:mm:ss',
  H_MM_SS_S: 'h:mm:ss.s',
  H_MM_SS_SS: 'h:mm:ss.ss',
  H_MM_SS_SSS: 'h:mm:ss.sss',
};

const DURATION_FORMATS = [
  { name: DURATION_FORMATS_MAP.H_MM, type: DURATION_FORMATS_MAP.H_MM },
  { name: DURATION_FORMATS_MAP.H_MM_SS, type: DURATION_FORMATS_MAP.H_MM_SS },
];

const DURATION_DECIMAL_DIGITS = {
  [DURATION_FORMATS_MAP.H_MM]: 0,
  [DURATION_FORMATS_MAP.H_MM_SS]: 0,
  [DURATION_FORMATS_MAP.H_MM_SS_S]: 1,
  [DURATION_FORMATS_MAP.H_MM_SS_SS]: 2,
  [DURATION_FORMATS_MAP.H_MM_SS_SSS]: 3,
};

export {
  DEFAULT_NUMBER_FORMAT,
  DURATION_FORMATS_MAP,
  DURATION_FORMATS,
  DURATION_DECIMAL_DIGITS,
};
